# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is script-generated 

LOCAL_PATH := vendor/honor/HWPLK

PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/proprietary/system/bin/6c8cf255-ca98-439e-a98e-ade64022ecb6.sec:system/bin/6c8cf255-ca98-439e-a98e-ade64022ecb6.sec \
    $(LOCAL_PATH)/proprietary/system/bin/9b17660b-8968-4eed-917e-dd32379bd548.sec:system/bin/9b17660b-8968-4eed-917e-dd32379bd548.sec \
    $(LOCAL_PATH)/proprietary/system/bin/79b77788-9789-4a7a-a2be-b60155eef5f4.sec:system/bin/79b77788-9789-4a7a-a2be-b60155eef5f4.sec \
    $(LOCAL_PATH)/proprietary/system/bin/883890ba-3ef8-4f0b-9c02-f5874acbf2ff.sec:system/bin/883890ba-3ef8-4f0b-9c02-f5874acbf2ff.sec \
    $(LOCAL_PATH)/proprietary/system/bin/a32b3d00-cb57-11e3-9c1a-0800200c9a66.sec:system/bin/a32b3d00-cb57-11e3-9c1a-0800200c9a66.sec \
    $(LOCAL_PATH)/proprietary/system/bin/abe89147-cd61-f43f-71c4-1a317e405312.sec:system/bin/abe89147-cd61-f43f-71c4-1a317e405312.sec \
    $(LOCAL_PATH)/proprietary/system/bin/b4b71581-add2-e89f-d536-f35436dc7973.sec:system/bin/b4b71581-add2-e89f-d536-f35436dc7973.sec \
    $(LOCAL_PATH)/proprietary/system/bin/knuckle_gestures.bin:system/bin/knuckle_gestures.bin \
    $(LOCAL_PATH)/proprietary/system/bin/afar:system/bin/afar \
    $(LOCAL_PATH)/proprietary/system/bin/atcmdserver:system/bin/atcmdserver \
    $(LOCAL_PATH)/proprietary/system/bin/chargelogcat:system/bin/chargelogcat \
    $(LOCAL_PATH)/proprietary/system/bin/chargemonitor:system/bin/chargemonitor \
    $(LOCAL_PATH)/proprietary/system/bin/diagserver:system/bin/diagserver \
    $(LOCAL_PATH)/proprietary/system/bin/dumptool:system/bin/dumptool \
    $(LOCAL_PATH)/proprietary/system/bin/eventcat:system/bin/eventcat \
    $(LOCAL_PATH)/proprietary/system/bin/fingerprintd:system/bin/fingerprintd \
    $(LOCAL_PATH)/proprietary/system/bin/gatekeeperd:system/bin/gatekeeperd \
    $(LOCAL_PATH)/proprietary/system/bin/gpsd:system/bin/gpsd \
    $(LOCAL_PATH)/proprietary/system/bin/gps.cer:system/bin/gps.cer \
    $(LOCAL_PATH)/proprietary/system/bin/gpsdaemon:system/bin/gpsdaemon \
    $(LOCAL_PATH)/proprietary/system/bin/gpslogd:system/bin/gpslogd \
    $(LOCAL_PATH)/proprietary/system/bin/hw_cdmamodem_service:system/bin/hw_cdmamodem_service \
    $(LOCAL_PATH)/proprietary/system/bin/HwCamCfgSvr:system/bin/HwCamCfgSvr \
    $(LOCAL_PATH)/proprietary/system/bin/hwclock:system/bin/hwclock \
    $(LOCAL_PATH)/proprietary/system/bin/hwnff:system/bin/hwnff \
    $(LOCAL_PATH)/proprietary/system/bin/hwnffserver:system/bin/hwnffserver \
    $(LOCAL_PATH)/proprietary/system/bin/hwpged:system/bin/hwpged \
    $(LOCAL_PATH)/proprietary/system/bin/logcat:system/bin/logcat \
    $(LOCAL_PATH)/proprietary/system/bin/logserver:system/bin/logserver \
    $(LOCAL_PATH)/proprietary/system/bin/keystore:system/bin/keystore \
    $(LOCAL_PATH)/proprietary/system/bin/mac_addr_normalization:system/bin/mac_addr_normalization \
    $(LOCAL_PATH)/proprietary/system/bin/mediaserver:system/bin/mediaserver \
    $(LOCAL_PATH)/proprietary/system/bin/modemlogcat_lte:system/bin/modemlogcat_lte \
    $(LOCAL_PATH)/proprietary/system/bin/modemlogcat_via:system/bin/modemlogcat_via \
    $(LOCAL_PATH)/proprietary/system/bin/pppd:system/bin/pppd \
    $(LOCAL_PATH)/proprietary/system/bin/pppoe:system/bin/pppoe \
    $(LOCAL_PATH)/proprietary/system/bin/powerlogd:system/bin/powerlogd \
    $(LOCAL_PATH)/proprietary/system/bin/rild:system/bin/rild \
    $(LOCAL_PATH)/proprietary/system/bin/secure_storage:system/bin/secure_storage \
    $(LOCAL_PATH)/proprietary/system/bin/thermal-daemon:system/bin/thermal-daemon \
    $(LOCAL_PATH)/proprietary/system/bin/wifiwakeupsrc:system/bin/wifiwakeupsrc \
    $(LOCAL_PATH)/proprietary/system/fpgaice40/PLK-AL10-VA.bin:system/fpgaice40/PLK-AL10-VA.bin \
    $(LOCAL_PATH)/proprietary/system/fpgaice40/PLK-AL10-VA.txt:system/fpgaice40/PLK-AL10-VA.txt \
    $(LOCAL_PATH)/proprietary/system/fpgaice40/PLK-CL00-VA.bin:system/fpgaice40/PLK-CL00-VA.bin \
    $(LOCAL_PATH)/proprietary/system/fpgaice40/PLK-CL00-VA.txt:system/fpgaice40/PLK-CL00-VA.txt \
    $(LOCAL_PATH)/proprietary/system/fpgaice40/PLK-L01-VA.bin:system/fpgaice40/PLK-L01-VA.bin \
    $(LOCAL_PATH)/proprietary/system/fpgaice40/PLK-L01-VA.txt:system/fpgaice40/PLK-L01-VA.txt \
    $(LOCAL_PATH)/proprietary/system/fpgaice40/PLK-L02-VA.bin:system/fpgaice40/PLK-L02-VA.bin \
    $(LOCAL_PATH)/proprietary/system/fpgaice40/PLK-L02-VA.txt:system/fpgaice40/PLK-L02-VA.txt \
    $(LOCAL_PATH)/proprietary/system/fpgaice40/PLK-TL00-VA.bin:system/fpgaice40/PLK-TL00-VA.bin \
    $(LOCAL_PATH)/proprietary/system/fpgaice40/PLK-TL00-VA.txt:system/fpgaice40/PLK-TL00-VA.txt \
    $(LOCAL_PATH)/proprietary/system/fpgaice40/PLK-TL01H-VA.bin:system/fpgaice40/PLK-TL01H-VA.bin \
    $(LOCAL_PATH)/proprietary/system/fpgaice40/PLK-TL01H-VA.txt:system/fpgaice40/PLK-TL01H-VA.txt \
    $(LOCAL_PATH)/proprietary/system/fpgaice40/PLK-UL00-VA.bin:system/fpgaice40/PLK-UL00-VA.bin \
    $(LOCAL_PATH)/proprietary/system/fpgaice40/PLK-UL00-VA.txt:system/fpgaice40/PLK-UL00-VA.txt \
    $(LOCAL_PATH)/proprietary/system/etc/audio/algorithm/algorithm_hi3635_normal.xml:system/etc/audio/algorithm/algorithm_hi3635_normal.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/algorithm/algorithm_hi3635cs_normal.xml:system/etc/audio/algorithm/algorithm_hi3635cs_normal.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/algorithm/algorithm_PLK_AL_normal.xml:system/etc/audio/algorithm/algorithm_PLK_AL_normal.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/algorithm/algorithm_PLK_CL_normal.xml:system/etc/audio/algorithm/algorithm_PLK_CL_normal.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/algorithm/algorithm_PLK_L01_normal.xml:system/etc/audio/algorithm/algorithm_PLK_L01_normal.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/algorithm/ascend_algorithm_default.xml:system/etc/audio/algorithm/ascend_algorithm_default.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/dts/dts_default.xml:system/etc/audio/dts/dts_default.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/dts/dts_hi3635_normal.xml:system/etc/audio/dts/dts_hi3635_normal.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/dts/dts_hi3635cs_normal.xml:system/etc/audio/dts/dts_hi3635cs_normal.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/dts/dts_PLK_AL_normal.xml:system/etc/audio/dts/dts_PLK_AL_normal.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/dts/dts_PLK_CL_normal.xml:system/etc/audio/dts/dts_PLK_CL_normal.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/dts/dts_default.xml:system/etc/audio/dts/dts_default.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/maxim/maxim_hi3635_normal.xml:system/etc/audio/maxim/maxim_hi3635_normal.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/maxim/maxim_hi3635cs_normal.xml:system/etc/audio/maxim/maxim_hi3635cs_normal.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/maxim/maxim_PLK_AL_normal.xml:system/etc/audio/maxim/maxim_PLK_AL_normal.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/maxim/maxim_PLK_CL_normal.xml:system/etc/audio/maxim/maxim_PLK_CL_normal.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/maxim/maxim_PLK_L01_normal.xml:system/etc/audio/maxim/maxim_PLK_L01_normal.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/maxim/maxim_PLK_L02_normal.xml:system/etc/audio/maxim/maxim_PLK_L02_normal.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/maxim/maxim_PLK_TL_normal.xml:system/etc/audio/maxim/maxim_PLK_TL_normal.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/maxim/maxim_PLK_UL_normal.xml:system/etc/audio/maxim/maxim_PLK_UL_normal.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/mbdrc/mbdrc_hi3635_normal.xml:system/etc/audio/mbdrc/mbdrc_hi3635_normal.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/mbdrc/mbdrc_hi3635cs_normal.xml:system/etc/audio/mbdrc/mbdrc_hi3635cs_normal.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/mbdrc/mbdrc_PLK_AL_normal.xml:system/etc/audio/mbdrc/mbdrc_PLK_AL_normal.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/mbdrc/mbdrc_PLK_CL_normal.xml:system/etc/audio/mbdrc/mbdrc_PLK_CL_normal.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/mbdrc/mbdrc_PLK_L01_normal.xml:system/etc/audio/mbdrc/mbdrc_PLK_L01_normal.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/mbdrc/mbdrc_PLK_L02_normal.xml:system/etc/audio/mbdrc/mbdrc_PLK_L02_normal.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/mbdrc/mbdrc_PLK_TL_normal.xml:system/etc/audio/mbdrc/mbdrc_PLK_TL_normal.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/mbdrc/mbdrc_PLK_UL_normal.xml:system/etc/audio/mbdrc/mbdrc_PLK_UL_normal.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/nxp/Tfa9895_default.cnt:system/etc/audio/nxp/Tfa9895_default.cnt \
    $(LOCAL_PATH)/proprietary/system/etc/audio/nxp/Tfa9895_MOZART.cnt:system/etc/audio/nxp/Tfa9895_MOZART.cnt \
    $(LOCAL_PATH)/proprietary/system/etc/audio/nxp/Tfa9895_MOZART_coefficient.config:system/etc/audio/nxp/Tfa9895_MOZART_coefficient.config \
    $(LOCAL_PATH)/proprietary/system/etc/audio/nxp/Tfa9895_MOZART_sec.cnt:system/etc/audio/nxp/Tfa9895_MOZART_sec.cnt \
    $(LOCAL_PATH)/proprietary/system/etc/audio/sws/sws_default.xml:system/etc/audio/sws/sws_default.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/sws/sws_LISZT_normal.xml:system/etc/audio/sws/sws_LISZT_normal.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/sws/sws_MOZART_normal.xml:system/etc/audio/sws/sws_MOZART_normal.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/hi6402/mixer_paths_default.xml:system/etc/audio/hi6402/mixer_paths_default.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/hi6402/mixer_paths_hi3635.xml:system/etc/audio/hi6402/mixer_paths_hi3635.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/hi6402/mixer_paths_hi3635cs.xml:system/etc/audio/hi6402/mixer_paths_hi3635cs.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/hi6402/mixer_paths_hi3635fpga.xml:system/etc/audio/hi6402/mixer_paths_hi3635fpga.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/hi6402/mixer_paths_PLK.xml:system/etc/audio/hi6402/mixer_paths_PLK.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/hi6402/mixer_volumes_default.xml:system/etc/audio/hi6402/mixer_volumes_default.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/hi6402/mixer_volumes_hi3635_normal.xml:system/etc/audio/hi6402/mixer_volumes_hi3635_normal.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/hi6402/mixer_volumes_hi3635cs_normal.xml:system/etc/audio/hi6402/mixer_volumes_hi3635cs_normal.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/hi6402/mixer_volumes_hi3635fpga_normal.xml:system/etc/audio/hi6402/mixer_volumes_hi3635fpga_normal.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/hi6402/mixer_volumes_PLK_AL_ce.xml:system/etc/audio/hi6402/mixer_volumes_PLK_AL_ce.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/hi6402/mixer_volumes_PLK_AL_normal.xml:system/etc/audio/hi6402/mixer_volumes_PLK_AL_normal.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/hi6402/mixer_volumes_PLK_CL_ce.xml:system/etc/audio/hi6402/mixer_volumes_PLK_CL_ce.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/hi6402/mixer_volumes_PLK_CL_normal.xml:system/etc/audio/hi6402/mixer_volumes_PLK_CL_normal.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/hi6402/mixer_volumes_PLK_cmcciot.xml:system/etc/audio/hi6402/mixer_volumes_PLK_cmcciot.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/hi6402/mixer_volumes_PLK_L01_ce.xml:system/etc/audio/hi6402/mixer_volumes_PLK_L01_ce.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/hi6402/mixer_volumes_PLK_L01_normal.xml:system/etc/audio/hi6402/mixer_volumes_PLK_L01_normal.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/hi6402/pop_seq_default.xml:system/etc/audio/hi6402/pop_seq_default.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/hi6402/pop_seq_hi3635.xml:system/etc/audio/hi6402/pop_seq_hi3635.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/hi6402/pop_seq_hi3635cs.xml:system/etc/audio/hi6402/pop_seq_hi3635cs.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/hi6402/pop_seq_hi3635fpga.xml:system/etc/audio/hi6402/pop_seq_hi3635fpga.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/hi6402/pop_seq_PLK.xml:system/etc/audio/hi6402/pop_seq_PLK.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/modem/modem_default.xml:system/etc/audio/modem/modem_default.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/modem/modem_hi3635_normal.xml:system/etc/audio/modem/modem_hi3635_normal.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/modem/modem_hi3635cs_normal.xml:system/etc/audio/modem/modem_hi3635cs_normal.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/modem/modem_PLK_AL_normal.xml:system/etc/audio/modem/modem_PLK_AL_normal.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/modem/modem_PLK_CL_normal.xml:system/etc/audio/modem/modem_PLK_CL_normal.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/modem/modem_PLK_cmcciot.xml:system/etc/audio/modem/modem_PLK_cmcciot.xml \
    $(LOCAL_PATH)/proprietary/system/etc/audio/modem/modem_PLK_L01_normal.xml:system/etc/audio/modem/modem_PLK_L01_normal.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/bshutter/default/algo.xml:system/etc/camera/bshutter/default/algo.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/bshutter/default/info.xml:system/etc/camera/bshutter/default/info.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/bshutter/imx179/algo.xml:system/etc/camera/bshutter/imx179/algo.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/bshutter/imx179/info.xml:system/etc/camera/bshutter/imx179/info.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/bshutter/imx230/algo.xml:system/etc/camera/bshutter/imx230/algo.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/bshutter/imx230/info.xml:system/etc/camera/bshutter/imx230/info.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/bshutter/imx278/algo.xml:system/etc/camera/bshutter/imx278/algo.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/bshutter/imx278/info.xml:system/etc/camera/bshutter/imx278/info.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/bshutter/ov8865/algo.xml:system/etc/camera/bshutter/ov8865/algo.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/bshutter/device.config:system/etc/camera/bshutter/device.config \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/default/cm_correction.dat:system/etc/camera/davinci/default/cm_correction.dat \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/default/cm_foliage.dat:system/etc/camera/davinci/default/cm_foliage.dat \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/default/cm_normal.dat:system/etc/camera/davinci/default/cm_normal.dat \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/default/cm_sky.dat:system/etc/camera/davinci/default/cm_sky.dat \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/default/cm_sunset.dat:system/etc/camera/davinci/default/cm_sunset.dat \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/default/hdr.xml:system/etc/camera/davinci/default/hdr.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/default/imgproc.xml:system/etc/camera/davinci/default/imgproc.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/default/multiframe.xml:system/etc/camera/davinci/default/multiframe.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/device.config:system/etc/camera/davinci/device.config \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/imx179_front/multiframe.xml:system/etc/camera/davinci/imx179_front/multiframe.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/imx179_front/hdr.xml:system/etc/camera/davinci/imx179_front/hdr.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/imx179_front/imgproc.xml:system/etc/camera/davinci/imx179_front/imgproc.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/imx179_front_plk/multiframe.xml:system/etc/camera/davinci/imx179_front_plk/multiframe.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/imx179_front_plk/hdr.xml:system/etc/camera/davinci/imx179_front_plk/hdr.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/imx179_front_plk/imgproc.xml:system/etc/camera/davinci/imx179_front_plk/imgproc.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/imx219/multiframe.xml:system/etc/camera/davinci/imx219/multiframe.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/imx219/hdr.xml:system/etc/camera/davinci/imx219/hdr.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/imx219/imgproc.xml:system/etc/camera/davinci/imx219/imgproc.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/imx230/multiframe.xml:system/etc/camera/davinci/imx230/multiframe.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/imx230/hdr.xml:system/etc/camera/davinci/imx230/hdr.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/imx230/imgproc.xml:system/etc/camera/davinci/imx230/imgproc.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/imx230/NICEFOOD/imgproc.xml:system/etc/camera/davinci/imx230/NICEFOOD/imgproc.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/imx278/multiframe.xml:system/etc/camera/davinci/imx278/multiframe.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/imx278/hdr.xml:system/etc/camera/davinci/imx278/hdr.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/imx278/imgproc.xml:system/etc/camera/davinci/imx278/imgproc.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/imx328/multiframe.xml:system/etc/camera/davinci/imx328/multiframe.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/imx328/hdr.xml:system/etc/camera/davinci/imx328/hdr.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/imx328/imgproc.xml:system/etc/camera/davinci/imx328/imgproc.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/mt9d015/multiframe.xml:system/etc/camera/davinci/mt9d015/multiframe.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/mt9d015/hdr.xml:system/etc/camera/davinci/mt9d015/hdr.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/mt9d015/imgproc.xml:system/etc/camera/davinci/mt9d015/imgproc.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/ov13850/multiframe.xml:system/etc/camera/davinci/ov13850/multiframe.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/ov13850/hdr.xml:system/etc/camera/davinci/ov13850/hdr.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/ov13850/imgproc.xml:system/etc/camera/davinci/ov13850/imgproc.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/ov2680/multiframe.xml:system/etc/camera/davinci/ov2680/multiframe.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/ov2680/hdr.xml:system/etc/camera/davinci/ov2680/hdr.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/ov2680/imgproc.xml:system/etc/camera/davinci/ov2680/imgproc.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/ov5648_x1s/multiframe.xml:system/etc/camera/davinci/ov5648_x1s/multiframe.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/ov5648_x1s/hdr.xml:system/etc/camera/davinci/ov5648_x1s/hdr.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/ov5648_x1s/imgproc.xml:system/etc/camera/davinci/ov5648_x1s/imgproc.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/ov8858/multiframe.xml:system/etc/camera/davinci/ov8858/multiframe.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/ov8858/hdr.xml:system/etc/camera/davinci/ov8858/hdr.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/ov8858/imgproc.xml:system/etc/camera/davinci/ov8858/imgproc.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/ov8865/multiframe.xml:system/etc/camera/davinci/ov8865/multiframe.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/ov8865/hdr.xml:system/etc/camera/davinci/ov8865/hdr.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/ov8865/imgproc.xml:system/etc/camera/davinci/ov8865/imgproc.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/ov8865_front/multiframe.xml:system/etc/camera/davinci/ov8865_front/multiframe.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/ov8865_front/hdr.xml:system/etc/camera/davinci/ov8865_front/hdr.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/ov8865_front/imgproc.xml:system/etc/camera/davinci/ov8865_front/imgproc.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/s5k4e1ga/multiframe.xml:system/etc/camera/davinci/s5k4e1ga/multiframe.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/s5k4e1ga/hdr.xml:system/etc/camera/davinci/s5k4e1ga/hdr.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/s5k4e1ga/imgproc.xml:system/etc/camera/davinci/s5k4e1ga/imgproc.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/davinci/davinciclkernel.bin:system/etc/camera/davinci/davinciclkernel.bin \
    $(LOCAL_PATH)/proprietary/system/etc/camera/dcsr/dcsr.xml:system/etc/camera/dcsr/dcsr.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/dcsr/dcsr_kernel:system/etc/camera/dcsr/dcsr_kernel \
    $(LOCAL_PATH)/proprietary/system/etc/camera/dcvalidation.xml:system/etc/camera/dcvalidation.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/dflash/calibration_000.txt:system/etc/camera/dflash/calibration_000.txt \
    $(LOCAL_PATH)/proprietary/system/etc/camera/dflash/calibration_001.txt:system/etc/camera/dflash/calibration_001.txt \
    $(LOCAL_PATH)/proprietary/system/etc/camera/dflash/calibration_002.txt:system/etc/camera/dflash/calibration_002.txt \
    $(LOCAL_PATH)/proprietary/system/etc/camera/dflash/calibration_003.txt:system/etc/camera/dflash/calibration_003.txt \
    $(LOCAL_PATH)/proprietary/system/etc/camera/dflash/calibration_004.txt:system/etc/camera/dflash/calibration_004.txt \
    $(LOCAL_PATH)/proprietary/system/etc/camera/dflash/calibration_005.txt:system/etc/camera/dflash/calibration_005.txt \
    $(LOCAL_PATH)/proprietary/system/etc/camera/dflash/calibration_006.txt:system/etc/camera/dflash/calibration_006.txt \
    $(LOCAL_PATH)/proprietary/system/etc/camera/dflash/calibration_007.txt:system/etc/camera/dflash/calibration_007.txt \
    $(LOCAL_PATH)/proprietary/system/etc/camera/dflash/calibration_008.txt:system/etc/camera/dflash/calibration_008.txt \
    $(LOCAL_PATH)/proprietary/system/etc/camera/dflash/calibration_009.txt:system/etc/camera/dflash/calibration_009.txt \
    $(LOCAL_PATH)/proprietary/system/etc/camera/dflash/calibration_010.txt:system/etc/camera/dflash/calibration_010.txt \
    $(LOCAL_PATH)/proprietary/system/etc/camera/dflash/calibration_011.txt:system/etc/camera/dflash/calibration_011.txt \
    $(LOCAL_PATH)/proprietary/system/etc/camera/dflash/calibration_012.txt:system/etc/camera/dflash/calibration_012.txt \
    $(LOCAL_PATH)/proprietary/system/etc/camera/dflash/calibration_013.txt:system/etc/camera/dflash/calibration_013.txt \
    $(LOCAL_PATH)/proprietary/system/etc/camera/dflash/calibration_014.txt:system/etc/camera/dflash/calibration_014.txt \
    $(LOCAL_PATH)/proprietary/system/etc/camera/dflash/calibration_015.txt:system/etc/camera/dflash/calibration_015.txt \
    $(LOCAL_PATH)/proprietary/system/etc/camera/dflash/calibration_016.txt:system/etc/camera/dflash/calibration_016.txt \
    $(LOCAL_PATH)/proprietary/system/etc/camera/dflash/calibration_017.txt:system/etc/camera/dflash/calibration_017.txt \
    $(LOCAL_PATH)/proprietary/system/etc/camera/dflash/calibration_018.txt:system/etc/camera/dflash/calibration_018.txt \
    $(LOCAL_PATH)/proprietary/system/etc/camera/dflash/calibration_019.txt:system/etc/camera/dflash/calibration_019.txt \
    $(LOCAL_PATH)/proprietary/system/etc/camera/dflash/calibration_020.txt:system/etc/camera/dflash/calibration_020.txt \
    $(LOCAL_PATH)/proprietary/system/etc/camera/dflash/calPara4Selection.txt:system/etc/camera/dflash/calPara4Selection.txt \
    $(LOCAL_PATH)/proprietary/system/etc/camera/dflash/flash_current.txt:system/etc/camera/dflash/flash_current.txt \
    $(LOCAL_PATH)/proprietary/system/etc/camera/dflash/limitationgain.txt:system/etc/camera/dflash/limitationgain.txt \
    $(LOCAL_PATH)/proprietary/system/etc/camera/dflash/manual_flash_level.txt:system/etc/camera/dflash/manual_flash_level.txt \
    $(LOCAL_PATH)/proprietary/system/etc/camera/filter/filter.xml:system/etc/camera/filter/filter.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/filter/mixIm.dat:system/etc/camera/filter/mixIm.dat \
    $(LOCAL_PATH)/proprietary/system/etc/camera/hwaae/device.config:system/etc/camera/hwaae/device.config \
    $(LOCAL_PATH)/proprietary/system/etc/camera/hwaae/imx219/HwaAePara.xml:system/etc/camera/hwaae/imx219/HwaAePara.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/hwaae/mt9d015/HwaAePara.xml:system/etc/camera/hwaae/mt9d015/HwaAePara.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/hwaae/ov2680/HwaAePara.xml:system/etc/camera/hwaae/ov2680/HwaAePara.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/hwaae/ov8858/HwaAePara.xml:system/etc/camera/hwaae/ov8858/HwaAePara.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/hwaflash/device.config:system/etc/camera/hwaflash/device.config \
    $(LOCAL_PATH)/proprietary/system/etc/camera/hwaflash/imx219/HwaFlashPara.xml:system/etc/camera/hwaflash/imx219/HwaFlashPara.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/hwaflash/mt9d015/HwaFlashPara.xml:system/etc/camera/hwaflash/mt9d015/HwaFlashPara.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/hwaflash/ov2680/HwaFlashPara.xml:system/etc/camera/hwaflash/ov2680/HwaFlashPara.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/hwaflash/ov8858/HwaFlashPara.xml:system/etc/camera/hwaflash/ov8858/HwaFlashPara.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/hwldc/device.config:system/etc/camera/hwldc/device.config \
    $(LOCAL_PATH)/proprietary/system/etc/camera/hwldc/imx179_front/hwldc_config.xml:system/etc/camera/hwldc/imx179_front/hwldc_config.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/hwldc/imx179_front_liteon/hwldc_config.xml:system/etc/camera/hwldc/imx179_front_liteon/hwldc_config.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/hwldc/imx179_front_plk_liteon/hwldc_config.xml:system/etc/camera/hwldc/imx179_front_plk_liteon/hwldc_config.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/hwldc/imx179_front_plk_sunny/hwldc_config.xml:system/etc/camera/hwldc/imx179_front_plk_sunny/hwldc_config.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/hwldc/imx179_front_sunny/hwldc_config.xml:system/etc/camera/hwldc/imx179_front_sunny/hwldc_config.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/hwscope/device.config:system/etc/camera/hwscope/device.config \
    $(LOCAL_PATH)/proprietary/system/etc/camera/hwscope/default/hwsz.xml:system/etc/camera/hwscope/default/hwsz.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/hwscope/default/kernel:system/etc/camera/hwscope/default/kernel \
    $(LOCAL_PATH)/proprietary/system/etc/camera/hwscope/PLK_imx230/hwsz.xml:system/etc/camera/hwscope/PLK_imx230/hwsz.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/hwscope/PLK_imx230/kernel:system/etc/camera/hwscope/PLK_imx230/kernel \
    $(LOCAL_PATH)/proprietary/system/etc/camera/multidenoise/device.config:system/etc/camera/multidenoise/device.config \
    $(LOCAL_PATH)/proprietary/system/etc/camera/multidenoise/multidenoise.xml:system/etc/camera/multidenoise/multidenoise.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/multidenoise/default/multiframe.xml:system/etc/camera/multidenoise/default/multiframe.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/nicefood/device.config:system/etc/camera/nicefood/device.config \
    $(LOCAL_PATH)/proprietary/system/etc/camera/nicefood/default/niceFood.dat:system/etc/camera/nicefood/default/niceFood.dat \
    $(LOCAL_PATH)/proprietary/system/etc/camera/smartae/device.config:system/etc/camera/smartae/device.config \
    $(LOCAL_PATH)/proprietary/system/etc/camera/smartae/imx230_lg/SmartAE.xml:system/etc/camera/smartae/imx230_lg/SmartAE.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/smartae/imx230_liteon/SmartAE.xml:system/etc/camera/smartae/imx230_liteon/SmartAE.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/smartae/imx230_sunny/SmartAE.xml:system/etc/camera/smartae/imx230_sunny/SmartAE.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/smartae/imx278_lg/SmartAE.xml:system/etc/camera/smartae/imx278_lg/SmartAE.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/smartae/imx278_liteon/SmartAE.xml:system/etc/camera/smartae/imx278_liteon/SmartAE.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/smartae/imx230_sunny/SmartAE.xml:system/etc/camera/smartae/imx230_sunny/SmartAE.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/smartae/ov13850/SmartAE.xml:system/etc/camera/smartae/ov13850/SmartAE.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/tornado/device.config:system/etc/camera/tornado/device.config \
    $(LOCAL_PATH)/proprietary/system/etc/camera/tornado/FoliageMinMaxTOA.txt:system/etc/camera/tornado/FoliageMinMaxTOA.txt \
    $(LOCAL_PATH)/proprietary/system/etc/camera/tornado/FoliageModelTOA.model:system/etc/camera/tornado/FoliageModelTOA.model \
    $(LOCAL_PATH)/proprietary/system/etc/camera/tornado/NightMinMaxTOA.txt:system/etc/camera/tornado/NightMinMaxTOA.txt \
    $(LOCAL_PATH)/proprietary/system/etc/camera/tornado/NightModelTOA.model:system/etc/camera/tornado/NightModelTOA.model \
    $(LOCAL_PATH)/proprietary/system/etc/camera/tornado/SunsetMinMaxTOA.txt:system/etc/camera/tornado/SunsetMinMaxTOA.txt \
    $(LOCAL_PATH)/proprietary/system/etc/camera/tornado/SunsetModelTOA.model:system/etc/camera/tornado/SunsetModelTOA.model \
    $(LOCAL_PATH)/proprietary/system/etc/camera/tornado/default/TornadoI.ini:system/etc/camera/tornado/default/TornadoI.ini \
    $(LOCAL_PATH)/proprietary/system/etc/camera/tornado/imx179_front/TornadoI.ini:system/etc/camera/tornado/imx179_front/TornadoI.ini \
    $(LOCAL_PATH)/proprietary/system/etc/camera/tornado/imx179_front_plk_liteon/TornadoI.ini:system/etc/camera/tornado/imx179_front_plk_liteon/TornadoI.ini \
    $(LOCAL_PATH)/proprietary/system/etc/camera/tornado/imx179_front_plk_sunny/TornadoI.ini:system/etc/camera/tornado/imx179_front_plk_sunny/TornadoI.ini \
    $(LOCAL_PATH)/proprietary/system/etc/camera/tornado/imx219/TornadoI.ini:system/etc/camera/tornado/imx219/TornadoI.ini \
    $(LOCAL_PATH)/proprietary/system/etc/camera/tornado/imx230_lg/TornadoI.ini:system/etc/camera/tornado/imx230_lg/TornadoI.ini \
    $(LOCAL_PATH)/proprietary/system/etc/camera/tornado/imx230_liteon/TornadoI.ini:system/etc/camera/tornado/imx230_liteon/TornadoI.ini \
    $(LOCAL_PATH)/proprietary/system/etc/camera/tornado/imx230_sunny/TornadoI.ini:system/etc/camera/tornado/imx230_sunny/TornadoI.ini \
    $(LOCAL_PATH)/proprietary/system/etc/camera/tornado/imx278_lg/TornadoI.ini:system/etc/camera/tornado/imx278_lg/TornadoI.ini \
    $(LOCAL_PATH)/proprietary/system/etc/camera/tornado/imx278_liteon/TornadoI.ini:system/etc/camera/tornado/imx278_liteon/TornadoI.ini \
    $(LOCAL_PATH)/proprietary/system/etc/camera/tornado/imx278_sunny/TornadoI.ini:system/etc/camera/tornado/imx278_sunny/TornadoI.ini \
    $(LOCAL_PATH)/proprietary/system/etc/camera/tornado/mt9d015/TornadoI.ini:system/etc/camera/tornado/mt9d015/TornadoI.ini \
    $(LOCAL_PATH)/proprietary/system/etc/camera/tornado/ov2680/TornadoI.ini:system/etc/camera/tornado/ov2680/TornadoI.ini \
    $(LOCAL_PATH)/proprietary/system/etc/camera/tornado/ov5648/TornadoI.ini:system/etc/camera/tornado/ov5648/TornadoI.ini \
    $(LOCAL_PATH)/proprietary/system/etc/camera/tornado/ov8858/TornadoI.ini:system/etc/camera/tornado/ov8858/TornadoI.ini \
    $(LOCAL_PATH)/proprietary/system/etc/camera/tornado/ov8865/TornadoI.ini:system/etc/camera/tornado/ov8865/TornadoI.ini \
    $(LOCAL_PATH)/proprietary/system/etc/camera/tornado/ov13850/TornadoI.ini:system/etc/camera/tornado/ov13850/TornadoI.ini \
    $(LOCAL_PATH)/proprietary/system/etc/camera/tracking/targettracking.xml:system/etc/camera/tracking/targettracking.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/dcvalidation.xml:system/etc/camera/dcvalidation.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/ippalgoconfig.xml:system/etc/camera/ippalgoconfig.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/pdafvalidation.xml:system/etc/camera/pdafvalidation.xml \
    $(LOCAL_PATH)/proprietary/system/etc/camera/ppconfig.xml:system/etc/camera/ppconfig.xml \
    $(LOCAL_PATH)/proprietary/system/etc/modemConfig/hids_ue_msg.cfg:system/etc/modemConfig/hids_ue_msg.cfg \
    $(LOCAL_PATH)/proprietary/system/etc/modemConfig/hua.cfg:system/etc/modemConfig/hua.cfg \
    $(LOCAL_PATH)/proprietary/system/etc/modemConfig/viacbp82d_log.bcfg:system/etc/modemConfig/viacbp82d_log.bcfg \
    $(LOCAL_PATH)/proprietary/system/etc/modemConfig/viacbp82d_shutdown_log.bcfg:system/etc/modemConfig/viacbp82d_shutdown_log.bcfg \
    $(LOCAL_PATH)/proprietary/system/etc/modemConfig/balong/basic_name:system/etc/modemConfig/balong/basic_name \
    $(LOCAL_PATH)/proprietary/system/etc/modemConfig/balong/FieldTest.cfg:system/etc/modemConfig/balong/FieldTest.cfg \
    $(LOCAL_PATH)/proprietary/system/etc/srs/models.txt:system/etc/srs/models.txt \
    $(LOCAL_PATH)/proprietary/system/etc/srs/srs_processing.cfg:system/etc/srs/srs_processing.cfg \
    $(LOCAL_PATH)/proprietary/system/etc/srs/srsmodels.lic:system/etc/srs/srsmodels.lic \
    $(LOCAL_PATH)/proprietary/system/etc/wifi/p2p_supplicant_overlay.conf:system/etc/wifi/p2p_supplicant_overlay.conf \
    $(LOCAL_PATH)/proprietary/system/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
    $(LOCAL_PATH)/proprietary/system/etc/wifi/wpa_supplicant_overlay.conf:system/etc/wifi/wpa_supplicant_overlay.conf \
    $(LOCAL_PATH)/proprietary/system/etc/audio_effects.conf:system/etc/audio_effects.conf \
    $(LOCAL_PATH)/proprietary/system/etc/audio_policy.conf:system/etc/audio_policy.conf \
    $(LOCAL_PATH)/proprietary/system/etc/backlight_policy.xml:system/etc/backlight_policy.xml \
    $(LOCAL_PATH)/proprietary/system/etc/chargemonitor_config.xml:system/etc/chargemonitor_config.xml \
    $(LOCAL_PATH)/proprietary/system/etc/device_monitor_for_nff.conf:system/etc/device_monitor_for_nff.conf \
    $(LOCAL_PATH)/proprietary/system/etc/factory_modem.cfg:system/etc/factory_modem.cfg \
    $(LOCAL_PATH)/proprietary/system/etc/goldeneye_config.xml:system/etc/goldeneye_config.xml \
    $(LOCAL_PATH)/proprietary/system/etc/jankbdcfg.json:system/etc/jankbdcfg.json \
    $(LOCAL_PATH)/proprietary/system/etc/jankcfg.json:system/etc/jankcfg.json \
    $(LOCAL_PATH)/proprietary/system/etc/gps.conf:system/etc/gps.conf \
    $(LOCAL_PATH)/proprietary/system/etc/gps47531config.xml:system/etc/gps47531config.xml \
    $(LOCAL_PATH)/proprietary/system/etc/HwResourceManager.xml:system/etc/HwResourceManager.xml \
    $(LOCAL_PATH)/proprietary/system/etc/kerneldump.sh:system/etc/kerneldump.sh \
    $(LOCAL_PATH)/proprietary/system/etc/lsccir_config:system/etc/lsccir_config \
    $(LOCAL_PATH)/proprietary/system/etc/libnfc-brcm_PLK.conf:system/etc/libnfc-brcm_PLK.conf \
    $(LOCAL_PATH)/proprietary/system/etc/libnfc-nxp_PLK.conf:system/etc/libnfc-nxp_PLK.conf \
    $(LOCAL_PATH)/proprietary/system/etc/media_codecs.xml:system/etc/media_codecs.xml \
    $(LOCAL_PATH)/proprietary/system/etc/media_codecs_dts_audio.xml:system/etc/media_codecs_dts_audio.xml \
    $(LOCAL_PATH)/proprietary/system/etc/media_codecs_google_audio.xml:system/etc/media_codecs_google_audio.xml \
    $(LOCAL_PATH)/proprietary/system/etc/media_codecs_google_telephony.xml:system/etc/media_codecs_google_telephony.xml \
    $(LOCAL_PATH)/proprietary/system/etc/media_codecs_google_video.xml:system/etc/media_codecs_google_video.xml \
    $(LOCAL_PATH)/proprietary/system/etc/media_codecs_performance.xml:system/etc/media_codecs_performance.xml \
    $(LOCAL_PATH)/proprietary/system/etc/media_profiles.xml:system/etc/media_profiles.xml \
    $(LOCAL_PATH)/proprietary/system/etc/pwrlog.cfg:system/etc/pwrlog.cfg \
    $(LOCAL_PATH)/proprietary/system/etc/pwrprof.xml:system/etc/pwrprof.xml \
    $(LOCAL_PATH)/proprietary/system/etc/temperaturemonitor_setting.xml:system/etc/temperaturemonitor_setting.xml \
    $(LOCAL_PATH)/proprietary/system/etc/thermald.xml:system/etc/thermald.xml \
    $(LOCAL_PATH)/proprietary/system/etc/thermald_performance.xml:system/etc/thermald_performance.xml \
    $(LOCAL_PATH)/proprietary/system/etc/thermald_performance_qcoff.xml:system/etc/thermald_performance_qcoff.xml \
    $(LOCAL_PATH)/proprietary/system/etc/thermald_qcoff.xml:system/etc/thermald_qcoff.xml \
    $(LOCAL_PATH)/proprietary/system/etc/topazhp.cfg:system/etc/topazhp.cfg \
    $(LOCAL_PATH)/proprietary/system/etc/vdec_atlas.cfg:system/etc/vdec_atlas.cfg \
    $(LOCAL_PATH)/proprietary/system/etc/viacbp82d_log.bcfg:system/etc/viacbp82d_log.bcfg \
    $(LOCAL_PATH)/proprietary/system/etc/viacbp82d_shutdown_log.bcfg:system/etc/viacbp82d_shutdown_log.bcfg \
    $(LOCAL_PATH)/proprietary/system/isp/isp.bin:system/isp/isp.bin \
    $(LOCAL_PATH)/proprietary/system/global/apns-conf.xml:system/global/apns-conf.xml \
    $(LOCAL_PATH)/proprietary/system/global/apns-conf-nolte.xml:system/global/apns-conf-nolte.xml \
    $(LOCAL_PATH)/proprietary/system/global/globalAutoAdapt-conf.xml:system/global/globalAutoAdapt-conf.xml \
    $(LOCAL_PATH)/proprietary/system/global/globalMatchs-conf.xml:system/global/globalMatchs-conf.xml \
    $(LOCAL_PATH)/proprietary/system/global/version.txt:system/global/version.txt \
    $(LOCAL_PATH)/proprietary/system/global/virtualNets-conf.xml:system/global/virtualNets-conf.xml \
    $(LOCAL_PATH)/proprietary/system/global/voicemail-conf.xml:system/global/voicemail-conf.xml \
    $(LOCAL_PATH)/proprietary/system/global/ons/ons.bin:system/global/ons/ons.bin \
    $(LOCAL_PATH)/proprietary/system/global/xml/mccTable_V2.xml:system/global/xml/mccTable_V2.xml \
    $(LOCAL_PATH)/proprietary/system/lib/drm/libdrmhwomavoneplugin.so:system/lib/drm/libdrmhwomavoneplugin.so \
    $(LOCAL_PATH)/proprietary/system/lib/hw/audio.primary.hi3635.so:system/lib/hw/audio.primary.hi3635.so \
    $(LOCAL_PATH)/proprietary/system/lib/hw/camera.hi3635.so:system/lib/hw/camera.hi3635.so \
    $(LOCAL_PATH)/proprietary/system/lib/hw/consumerir.hi3635.so:system/lib/hw/consumerir.hi3635.so \
    $(LOCAL_PATH)/proprietary/system/lib/hw/copybit.hi3635.so:system/lib/hw/copybit.hi3635.so \
    $(LOCAL_PATH)/proprietary/system/lib/hw/displaycaps.default.so:system/lib/hw/displaycaps.default.so \
    $(LOCAL_PATH)/proprietary/system/lib/hw/fingerprint.hi3635.so:system/lib/hw/fingerprint.hi3635.so \
    $(LOCAL_PATH)/proprietary/system/lib/hw/fm.bcm.hi3635.so:system/lib/hw/fm.bcm.hi3635.so \
    $(LOCAL_PATH)/proprietary/system/lib/hw/gralloc.hi3635.so:system/lib/hw/gralloc.hi3635.so \
    $(LOCAL_PATH)/proprietary/system/lib/hw/gralloc.default.so:system/lib/hw/gralloc.default.so \
    $(LOCAL_PATH)/proprietary/system/lib/hw/hw_af_extend.default.so:system/lib/hw/hw_af_extend.default.so \
    $(LOCAL_PATH)/proprietary/system/lib/hw/irselflearning.default.so:system/lib/hw/irselflearning.default.so \
    $(LOCAL_PATH)/proprietary/system/lib/hw/keystore.hi3635.so:system/lib/hw/keystore.hi3635.so \
    $(LOCAL_PATH)/proprietary/system/lib/hw/lights.default.so:system/lib/hw/lights.default.so \
    $(LOCAL_PATH)/proprietary/system/lib/hw/memtrack.hi3635.so:system/lib/hw/memtrack.hi3635.so \
    $(LOCAL_PATH)/proprietary/system/lib/hw/power.hi3635.so:system/lib/hw/power.hi3635.so \
    $(LOCAL_PATH)/proprietary/system/lib/hw/power.default.so:system/lib/hw/power.default.so \
    $(LOCAL_PATH)/proprietary/system/lib/hw/sensorhub.default.so:system/lib/hw/sensorhub.default.so \
    $(LOCAL_PATH)/proprietary/system/lib/hw/sensorcaps.default.so:system/lib/hw/sensorcaps.default.so \
    $(LOCAL_PATH)/proprietary/system/lib/hw/vibrator.default.so:system/lib/hw/vibrator.default.so \
    $(LOCAL_PATH)/proprietary/system/lib/hwcam/hwcam.ddt.so:system/lib/hwcam/hwcam.ddt.so \
    $(LOCAL_PATH)/proprietary/system/lib/hwcam/hwcam.hi3635.m.PLK.so:system/lib/hwcam/hwcam.hi3635.m.PLK.so \
    $(LOCAL_PATH)/proprietary/system/lib/hwcam/hwcam.hi3635.PLK.p.imx179.so:system/lib/hwcam/hwcam.hi3635.PLK.p.imx179.so \
    $(LOCAL_PATH)/proprietary/system/lib/hwcam/hwcam.hi3635.PLK.p.imx179_liteon.so:system/lib/hwcam/hwcam.hi3635.PLK.p.imx179_liteon.so \
    $(LOCAL_PATH)/proprietary/system/lib/hwcam/hwcam.hi3635.PLK.p.imx179_sunny.so:system/lib/hwcam/hwcam.hi3635.PLK.p.imx179_sunny.so \
    $(LOCAL_PATH)/proprietary/system/lib/hwcam/hwcam.hi3635.PLK.p.imx230.so:system/lib/hwcam/hwcam.hi3635.PLK.p.imx230.so \
    $(LOCAL_PATH)/proprietary/system/lib/hwcam/hwcam.hi3635.PLK.p.imx230_lg.so:system/lib/hwcam/hwcam.hi3635.PLK.p.imx230_lg.so \
    $(LOCAL_PATH)/proprietary/system/lib/hwcam/hwcam.hi3635.PLK.p.imx230_liteon.so:system/lib/hwcam/hwcam.hi3635.PLK.p.imx230_liteon.so \
    $(LOCAL_PATH)/proprietary/system/lib/hwcam/hwcam.hi3635.PLK.p.imx230_sunny.so:system/lib/hwcam/hwcam.hi3635.PLK.p.imx230_sunny.so \
    $(LOCAL_PATH)/proprietary/system/lib/hwcam/hwcam.hi3635.PLK.p.imx230_liteon.so:system/lib/hwcam/hwcam.hi3635.PLK.p.imx230_liteon.so \
    $(LOCAL_PATH)/proprietary/system/lib/hwcam/hwcam.hi3635.PLK.s.imx179.so:system/lib/hwcam/hwcam.hi3635.PLK.s.imx179.so \
    $(LOCAL_PATH)/proprietary/system/lib/hwcam/hwcam.hi3635.PLK.s.imx179_liteon.so:system/lib/hwcam/hwcam.hi3635.PLK.s.imx179_liteon.so \
    $(LOCAL_PATH)/proprietary/system/lib/hwcam/hwcam.hi3635.PLK.s.imx179_sunny.so:system/lib/hwcam/hwcam.hi3635.PLK.s.imx179_sunny.so \
    $(LOCAL_PATH)/proprietary/system/lib/hwcam/hwcam.hi3635.PLK.s.imx230.so:system/lib/hwcam/hwcam.hi3635.PLK.s.imx230.so \
    $(LOCAL_PATH)/proprietary/system/lib/hwcam/hwcam.hi3635.PLK.s.imx230_lg.so:system/lib/hwcam/hwcam.hi3635.PLK.s.imx230_lg.so \
    $(LOCAL_PATH)/proprietary/system/lib/hwcam/hwcam.hi3635.PLK.s.imx230_liteon.so:system/lib/hwcam/hwcam.hi3635.PLK.s.imx230_liteon.so \
    $(LOCAL_PATH)/proprietary/system/lib/hwcam/hwcam.hi3635.PLK.s.imx230_sunny.so:system/lib/hwcam/hwcam.hi3635.PLK.s.imx230_sunny.so \
    $(LOCAL_PATH)/proprietary/system/lib/imedia_filters.so:system/lib/imedia_filters.so \
    $(LOCAL_PATH)/proprietary/system/lib/crtbegin_so.o:system/lib/crtbegin_so.o \
    $(LOCAL_PATH)/proprietary/system/lib/crtend_so.o:system/lib/crtend_so.o \
    $(LOCAL_PATH)/proprietary/system/lib/lib_k3_ffmpeg.so:system/lib/lib_k3_ffmpeg.so \
    $(LOCAL_PATH)/proprietary/system/lib/libaes.so:system/lib/libaes.so \
    $(LOCAL_PATH)/proprietary/system/lib/libaudio_custom.so:system/lib/libaudio_custom.so \
    $(LOCAL_PATH)/proprietary/system/lib/libaudioalgoservice_jni.so:system/lib/libaudioalgoservice_jni.so \
    $(LOCAL_PATH)/proprietary/system/lib/libaudioflinger.huawei.so:system/lib/libaudioflinger.huawei.so \
    $(LOCAL_PATH)/proprietary/system/lib/libaudiospdif.so:system/lib/libaudiospdif.so \
    $(LOCAL_PATH)/proprietary/system/lib/libaudiotestalgo.so:system/lib/libaudiotestalgo.so \
    $(LOCAL_PATH)/proprietary/system/lib/libbalong_audio_ril.so:system/lib/libbalong_audio_ril.so \
    $(LOCAL_PATH)/proprietary/system/lib/libbalong-ril.so:system/lib/libbalong-ril.so \
    $(LOCAL_PATH)/proprietary/system/lib/libbalong-ril-1.so:system/lib/libbalong-ril-1.so \
    $(LOCAL_PATH)/proprietary/system/lib/libBestShot.so:system/lib/libBestShot.so \
    $(LOCAL_PATH)/proprietary/system/lib/libbt_factory_test.so:system/lib/libbt_factory_test.so \
    $(LOCAL_PATH)/proprietary/system/lib/libbtaddrjni.so:system/lib/libbtaddrjni.so \
    $(LOCAL_PATH)/proprietary/system/lib/libcamera_ae.so:system/lib/libcamera_ae.so \
    $(LOCAL_PATH)/proprietary/system/lib/libcamera_af.so:system/lib/libcamera_af.so \
    $(LOCAL_PATH)/proprietary/system/lib/libcamera_algo.so:system/lib/libcamera_algo.so \
    $(LOCAL_PATH)/proprietary/system/lib/libcamera_flash.so:system/lib/libcamera_flash.so \
    $(LOCAL_PATH)/proprietary/system/lib/libcamera_client.so:system/lib/libcamera_client.so \
    $(LOCAL_PATH)/proprietary/system/lib/libCameraHwExtend.so:system/lib/libCameraHwExtend.so \
    $(LOCAL_PATH)/proprietary/system/lib/libcamera_metadata.so:system/lib/libcamera_metadata.so \
    $(LOCAL_PATH)/proprietary/system/lib/libcameraservice.so:system/lib/libcameraservice.so \
    $(LOCAL_PATH)/proprietary/system/lib/libffmpeg_neon.so:system/lib/libffmpeg_neon.so \
    $(LOCAL_PATH)/proprietary/system/lib/libfm_interface.so:system/lib/libfm_interface.so \
    $(LOCAL_PATH)/proprietary/system/lib/libfm_jni.so:system/lib/libfm_jni.so \
    $(LOCAL_PATH)/proprietary/system/lib/libfm_volume.so:system/lib/libfm_volume.so \
    $(LOCAL_PATH)/proprietary/system/lib/libgps_factory_test.so:system/lib/libgps_factory_test.so \
    $(LOCAL_PATH)/proprietary/system/lib/libgralloc_ext.default.so:system/lib/libgralloc_ext.default.so \
    $(LOCAL_PATH)/proprietary/system/lib/libgralloc_ext.so:system/lib/libgralloc_ext.so \
    $(LOCAL_PATH)/proprietary/system/lib/libhisi_efuse.so:system/lib/libhisi_efuse.so \
    $(LOCAL_PATH)/proprietary/system/lib/libhuaweiaudioalgoservice.so:system/lib/libhuaweiaudioalgoservice.so \
    $(LOCAL_PATH)/proprietary/system/lib/libhuaweiaudioeffectutil.so:system/lib/libhuaweiaudioeffectutil.so \
    $(LOCAL_PATH)/proprietary/system/lib/libhuaweiprocessing.so:system/lib/libhuaweiprocessing.so \
    $(LOCAL_PATH)/proprietary/system/lib/libhwaps.so:system/lib/libhwaps.so \
    $(LOCAL_PATH)/proprietary/system/lib/libhwgl.so:system/lib/libhwgl.so \
    $(LOCAL_PATH)/proprietary/system/lib/libhwuibp.so:system/lib/libhwuibp.so \
    $(LOCAL_PATH)/proprietary/system/lib/libHWCamCfgSvr.so:system/lib/libHWCamCfgSvr.so \
    $(LOCAL_PATH)/proprietary/system/lib/libHWCamCfgSvr_jni.so:system/lib/libHWCamCfgSvr_jni.so \
    $(LOCAL_PATH)/proprietary/system/lib/libjpu.so:system/lib/libjpu.so \
    $(LOCAL_PATH)/proprietary/system/lib/libmedialogservice.so:system/lib/libmedialogservice.so \
    $(LOCAL_PATH)/proprietary/system/lib/libpowerprofile.so:system/lib/libpowerprofile.so \
    $(LOCAL_PATH)/proprietary/system/lib/libril.so:system/lib/libril.so \
    $(LOCAL_PATH)/proprietary/system/lib/libreference-ril.so:system/lib/libreference-ril.so \
    $(LOCAL_PATH)/proprietary/system/lib/librilutils.so:system/lib/librilutils.so \
    $(LOCAL_PATH)/proprietary/system/lib/libscanner.so:system/lib/libscanner.so \
    $(LOCAL_PATH)/proprietary/system/lib/libsensorservice.so:system/lib/libsensorservice.so \
    $(LOCAL_PATH)/proprietary/system/lib/libservices.huawei.so:system/lib/libservices.huawei.so \
    $(LOCAL_PATH)/proprietary/system/lib/libteec.so:system/lib/libteec.so \
    $(LOCAL_PATH)/proprietary/system/lib/libvia-ril.so:system/lib/libvia-ril.so \
    $(LOCAL_PATH)/proprietary/system/lib/libvpp.so:system/lib/libvpp.so \
    $(LOCAL_PATH)/proprietary/system/lib/lib_atprotocolsw.so:system/lib/lib_atprotocolsw.so \
    $(LOCAL_PATH)/proprietary/system/lib/libatpswdck.so:system/lib/libatpswdck.so \
    $(LOCAL_PATH)/proprietary/system/lib/libaudioresampler.so:system/lib/libaudioresampler.so \
    $(LOCAL_PATH)/proprietary/system/lib/libaudioroute.so:system/lib/libaudioroute.so \
    $(LOCAL_PATH)/proprietary/system/lib/libcgroup.so:system/lib/libcgroup.so \
    $(LOCAL_PATH)/proprietary/system/lib/libcrypto2.so:system/lib/libcrypto2.so \
    $(LOCAL_PATH)/proprietary/system/lib/libdcamera_sr.so:system/lib/libdcamera_sr.so \
    $(LOCAL_PATH)/proprietary/system/lib/libdrmdecrypt.so:system/lib/libdrmdecrypt.so \
    $(LOCAL_PATH)/proprietary/system/lib/libffvplayer.so:system/lib/libffvplayer.so \
    $(LOCAL_PATH)/proprietary/system/lib/libhelixplayer.so:system/lib/libhelixplayer.so \
    $(LOCAL_PATH)/proprietary/system/lib/libhelixplayerwrapper.so:system/lib/libhelixplayerwrapper.so \
    $(LOCAL_PATH)/proprietary/system/lib/libHW_BShutter.so:system/lib/libHW_BShutter.so \
    $(LOCAL_PATH)/proprietary/system/lib/libhwdeviceinfo.so:system/lib/libhwdeviceinfo.so \
    $(LOCAL_PATH)/proprietary/system/lib/libhw_display_effect.so:system/lib/libhw_display_effect.so \
    $(LOCAL_PATH)/proprietary/system/lib/libhwdisplayprocess.so:system/lib/libhwdisplayprocess.so \
    $(LOCAL_PATH)/proprietary/system/lib/libhw_display_test.so:system/lib/libhw_display_test.so \
    $(LOCAL_PATH)/proprietary/system/lib/libhwextdevice.so:system/lib/libhwextdevice.so \
    $(LOCAL_PATH)/proprietary/system/lib/libHWExtDeviceService.so:system/lib/libHWExtDeviceService.so \
    $(LOCAL_PATH)/proprietary/system/lib/libHwExtendedExtractor.so:system/lib/libHwExtendedExtractor.so \
    $(LOCAL_PATH)/proprietary/system/lib/libHW_Pano_f.so:system/lib/libHW_Pano_f.so \
    $(LOCAL_PATH)/proprietary/system/lib/libhwsign.so:system/lib/libhwsign.so \
    $(LOCAL_PATH)/proprietary/system/lib/libhwtee_jni.so:system/lib/libhwtee_jni.so \
    $(LOCAL_PATH)/proprietary/system/lib/libHwTmr.so:system/lib/libHwTmr.so \
    $(LOCAL_PATH)/proprietary/system/lib/libjpegenchw.so:system/lib/libjpegenchw.so \
    $(LOCAL_PATH)/proprietary/system/lib/libmax98925.so:system/lib/libmax98925.so \
    $(LOCAL_PATH)/proprietary/system/lib/libnfc-nci.so:system/lib/libnfc-nci.so \
    $(LOCAL_PATH)/proprietary/system/lib/libnfc_nci_jni.so:system/lib/libnfc_nci_jni.so \
    $(LOCAL_PATH)/proprietary/system/lib/libnfc_ndef.so:system/lib/libnfc_ndef.so \
    $(LOCAL_PATH)/proprietary/system/lib/libnvme.so:system/lib/libnvme.so \
    $(LOCAL_PATH)/proprietary/system/lib/lib_nve_operation.so:system/lib/lib_nve_operation.so \
    $(LOCAL_PATH)/proprietary/system/lib/lib_oeminfo_interface.so:system/lib/lib_oeminfo_interface.so \
    $(LOCAL_PATH)/proprietary/system/lib/liboeminfo_jni.so:system/lib/liboeminfo_jni.so \
    $(LOCAL_PATH)/proprietary/system/lib/liboeminfo.so:system/lib/liboeminfo.so \
    $(LOCAL_PATH)/proprietary/system/lib/libSonyIMX230PdafLibrary.so:system/lib/libSonyIMX230PdafLibrary.so \
    $(LOCAL_PATH)/proprietary/system/lib/lib_vibrator.so:system/lib/lib_vibrator.so \
    $(LOCAL_PATH)/proprietary/system/lib/libion.so:system/lib/libion.so \
    $(LOCAL_PATH)/proprietary/system/lib/libsrsprocessing.so:system/lib/libsrsprocessing.so \
    $(LOCAL_PATH)/proprietary/system/lib/libSmartAE.so:system/lib/libSmartAE.so \
    $(LOCAL_PATH)/proprietary/system/lib/libSFBE.so:system/lib/libSFBE.so \
    $(LOCAL_PATH)/proprietary/system/lib/libTHImageOCR.so:system/lib/libTHImageOCR.so \
    $(LOCAL_PATH)/proprietary/system/lib/libpowergenie_native3.so:system/lib/libpowergenie_native3.so \
    $(LOCAL_PATH)/proprietary/system/lib64/drm/libdrmhwomavoneplugin.so:system/lib64/drm/libdrmhwomavoneplugin.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/audio.primary.hi3635.so:system/lib64/hw/audio.primary.hi3635.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/bastet.hi3635.so:system/lib64/hw/bastet.hi3635.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/camera.hi3635.so:system/lib64/hw/camera.hi3635.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/consumerir.hi3635.so:system/lib64/hw/consumerir.hi3635.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/copybit.hi3635.so:system/lib64/hw/copybit.hi3635.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/displaycaps.default.so:system/lib64/hw/displaycaps.default.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/fingerprint.hi3635.so:system/lib64/hw/fingerprint.hi3635.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/fingerprintd.ex.so:system/lib64/hw/fingerprintd.ex.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/flp.default.so:system/lib64/hw/flp.default.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/gatekeeper.hi3635.so:system/lib64/hw/gatekeeper.hi3635.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/gps.hi3635.so:system/lib64/hw/gps.hi3635.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/fm.bcm.hi3635.so:system/lib64/hw/fm.bcm.hi3635.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/gralloc.hi3635.so:system/lib64/hw/gralloc.hi3635.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/gralloc.default.so:system/lib64/hw/gralloc.default.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/irselflearning.default.so:system/lib64/hw/irselflearning.default.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/keystore.hi3635.so:system/lib64/hw/keystore.hi3635.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/lights.default.so:system/lib64/hw/lights.default.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/memtrack.hi3635.so:system/lib64/hw/memtrack.hi3635.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/nfc_nci.pn54x.default.so:system/lib64/hw/nfc_nci.pn54x.default.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/power.hi3635.so:system/lib64/hw/power.hi3635.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/power.default.so:system/lib64/hw/power.default.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/sensorhub.default.so:system/lib64/hw/sensorhub.default.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/sensorcaps.default.so:system/lib64/hw/sensorcaps.default.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/vibrator.default.so:system/lib64/hw/vibrator.default.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hwcam/hwcam.ddt.so:system/lib64/hwcam/hwcam.ddt.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hwcam/hwcam.hi3635.PLK.p.imx179.so:system/lib64/hwcam/hwcam.hi3635.PLK.p.imx179.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hwcam/hwcam.hi3635.PLK.p.imx179_liteon.so:system/lib64/hwcam/hwcam.hi3635.PLK.p.imx179_liteon.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hwcam/hwcam.hi3635.PLK.p.imx179_sunny.so:system/lib64/hwcam/hwcam.hi3635.PLK.p.imx179_sunny.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hwcam/hwcam.hi3635.PLK.p.imx230.so:system/lib64/hwcam/hwcam.hi3635.PLK.p.imx230.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hwcam/hwcam.hi3635.PLK.p.imx230_lg.so:system/lib64/hwcam/hwcam.hi3635.PLK.p.imx230_lg.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hwcam/hwcam.hi3635.PLK.p.imx230_liteon.so:system/lib64/hwcam/hwcam.hi3635.PLK.p.imx230_liteon.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hwcam/hwcam.hi3635.PLK.p.imx230_sunny.so:system/lib64/hwcam/hwcam.hi3635.PLK.p.imx230_sunny.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hwcam/hwcam.hi3635.PLK.p.imx230_liteon.so:system/lib64/hwcam/hwcam.hi3635.PLK.p.imx230_liteon.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hwcam/hwcam.hi3635.PLK.s.imx179.so:system/lib64/hwcam/hwcam.hi3635.PLK.s.imx179.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hwcam/hwcam.hi3635.PLK.s.imx179_liteon.so:system/lib64/hwcam/hwcam.hi3635.PLK.s.imx179_liteon.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hwcam/hwcam.hi3635.PLK.s.imx179_sunny.so:system/lib64/hwcam/hwcam.hi3635.PLK.s.imx179_sunny.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hwcam/hwcam.hi3635.PLK.s.imx230.so:system/lib64/hwcam/hwcam.hi3635.PLK.s.imx230.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hwcam/hwcam.hi3635.PLK.s.imx230_lg.so:system/lib64/hwcam/hwcam.hi3635.PLK.s.imx230_lg.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hwcam/hwcam.hi3635.PLK.s.imx230_liteon.so:system/lib64/hwcam/hwcam.hi3635.PLK.s.imx230_liteon.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hwcam/hwcam.hi3635.PLK.s.imx230_sunny.so:system/lib64/hwcam/hwcam.hi3635.PLK.s.imx230_sunny.so \
    $(LOCAL_PATH)/proprietary/system/lib64/crtbegin_so.o:system/lib64/crtbegin_so.o \
    $(LOCAL_PATH)/proprietary/system/lib64/crtend_so.o:system/lib64/crtend_so.o \
    $(LOCAL_PATH)/proprietary/system/lib64/lib_k3_ffmpeg.so:system/lib64/lib_k3_ffmpeg.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libaes.so:system/lib64/libaes.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libbastet.so:system/lib64/libbastet.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libaudio_custom.so:system/lib64/libaudio_custom.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libaudioalgoservice_jni.so:system/lib64/libaudioalgoservice_jni.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libaudiotestalgo.so:system/lib64/libaudiotestalgo.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libbalong_audio_ril.so:system/lib64/libbalong_audio_ril.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libbalong-ril.so:system/lib64/libbalong-ril.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libbalong-ril-1.so:system/lib64/libbalong-ril-1.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libbt_factory_test.so:system/lib64/libbt_factory_test.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libbtaddrjni.so:system/lib64/libbtaddrjni.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libcamera_client.so:system/lib64/libcamera_client.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libCameraHwExtend.so:system/lib64/libCameraHwExtend.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libcamera_metadata.so:system/lib64/libcamera_metadata.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libcameraservice.so:system/lib64/libcameraservice.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libfm_interface.so:system/lib64/libfm_interface.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libfm_jni.so:system/lib64/libfm_jni.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libfm_volume.so:system/lib64/libfm_volume.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libgps_factory_test.so:system/lib64/libgps_factory_test.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libgralloc_ext.default.so:system/lib64/libgralloc_ext.default.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libgralloc_ext.so:system/lib64/libgralloc_ext.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libhisi_efuse.so:system/lib64/libhisi_efuse.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libhuaweigpsrpc.so:system/lib64/libhuaweigpsrpc.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libhwuibp.so:system/lib64/libhwuibp.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libhwaps.so:system/lib64/libhwaps.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libhwgl.so:system/lib64/libhwgl.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libHWCamCfgSvr.so:system/lib64/libHWCamCfgSvr.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libHWCamCfgSvr_jni.so:system/lib64/libHWCamCfgSvr_jni.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libHWCamCfgSvr.so:system/lib64/libHWCamCfgSvr.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libjpu.so:system/lib64/libjpu.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libpowerprofile.so:system/lib64/libpowerprofile.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libril.so:system/lib64/libril.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libreference-ril.so:system/lib64/libreference-ril.so \
    $(LOCAL_PATH)/proprietary/system/lib64/librilutils.so:system/lib64/librilutils.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libsensorservice.so:system/lib64/libsensorservice.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libservices.huawei.so:system/lib64/libservices.huawei.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libteec.so:system/lib64/libteec.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libvia-ril.so:system/lib64/libvia-ril.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libvpp.so:system/lib64/libvpp.so \
    $(LOCAL_PATH)/proprietary/system/lib64/lib_atprotocolsw.so:system/lib64/lib_atprotocolsw.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libatpswdck.so:system/lib64/libatpswdck.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libaudio-resampler.so:system/lib64/libaudio-resampler.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libaudioroute.so:system/lib64/libaudioroute.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libcrypto2.so:system/lib64/libcrypto2.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libFingerprintMMITest.so:system/lib64/libFingerprintMMITest.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libfingersense.so:system/lib64/libfingersense.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libhwdeviceinfo.so:system/lib64/libhwdeviceinfo.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libhw_display_effect.so:system/lib64/libhw_display_effect.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libhwdisplayprocess.so:system/lib64/libhwdisplayprocess.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libhw_display_test.so:system/lib64/libhw_display_test.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libhwextdevice.so:system/lib64/libhwextdevice.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libHWExtDeviceService.so:system/lib64/libHWExtDeviceService.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libHwExtendedExtractor.so:system/lib64/libHwExtendedExtractor.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libhwsign.so:system/lib64/libhwsign.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libhwtee_jni.so:system/lib64/libhwtee_jni.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libHwTmr.so:system/lib64/libHwTmr.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libjpegenchw.so:system/lib64/libjpegenchw.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libmax98925.so:system/lib64/libmax98925.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libnfc-nci.so:system/lib64/libnfc-nci.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libnfc_nci_jni.so:system/lib64/libnfc_nci_jni.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libnfc_ndef.so:system/lib64/libnfc_ndef.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libnvme.so:system/lib64/libnvme.so \
    $(LOCAL_PATH)/proprietary/system/lib64/lib_nve_operation.so:system/lib64/lib_nve_operation.so \
    $(LOCAL_PATH)/proprietary/system/lib64/lib_oeminfo_interface.so:system/lib64/lib_oeminfo_interface.so \
    $(LOCAL_PATH)/proprietary/system/lib64/liboeminfo.so:system/lib64/liboeminfo.so \
    $(LOCAL_PATH)/proprietary/system/lib64/liboeminfo_jni.so:system/lib64/liboeminfo_jni.so \
    $(LOCAL_PATH)/proprietary/system/lib64/lib_vibrator.so:system/lib64/lib_vibrator.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libion.so:system/lib64/libion.so \
    $(LOCAL_PATH)/proprietary/system/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    $(LOCAL_PATH)/proprietary/system/lib/libstagefright.huawei.so:system/lib/libstagefright.huawei.so \
    $(LOCAL_PATH)/proprietary/system/lib/libstagefright_soft_ffmpegaudiodec.so:system/lib/libstagefright_soft_ffmpegaudiodec.so \
    $(LOCAL_PATH)/proprietary/system/lib/libstagefright_soft_ffmpegvideodec.so:system/lib/libstagefright_soft_ffmpegvideodec.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libstagefrighthw.so:system/lib64/libstagefrighthw.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libstagefright.huawei.so:system/lib64/libstagefright.huawei.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libstagefright_soft_ffmpegaudiodec.so:system/lib64/libstagefright_soft_ffmpegaudiodec.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libstagefright_soft_ffmpegvideodec.so:system/lib64/libstagefright_soft_ffmpegvideodec.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libpowergenie_native3.so:system/lib64/libpowergenie_native3.so \
    $(LOCAL_PATH)/proprietary/system/usr/idc/AVRCP.idc:system/usr/idc/AVRCP.idc \
    $(LOCAL_PATH)/proprietary/system/usr/idc/fingerprint.idc:system/usr/idc/fingerprint.idc \
    $(LOCAL_PATH)/proprietary/system/usr/idc/qwerty.idc:system/usr/idc/qwerty.idc \
    $(LOCAL_PATH)/proprietary/system/usr/idc/qwerty2.idc:system/usr/idc/qwerty2.idc \
    $(LOCAL_PATH)/proprietary/system/usr/keychars/Generic.kcm:system/usr/keychars/Generic.kcm \
    $(LOCAL_PATH)/proprietary/system/usr/keychars/qwerty.kcm:system/usr/keychars/qwerty.kcm \
    $(LOCAL_PATH)/proprietary/system/usr/keychars/qwerty2.kcm:system/usr/keychars/qwerty2.kcm \
    $(LOCAL_PATH)/proprietary/system/usr/keychars/Virtual.kcm:system/usr/keychars/Virtual.kcm \
    $(LOCAL_PATH)/proprietary/system/usr/keylayout/AVRCP.kl:system/usr/keylayout/AVRCP.kl \
    $(LOCAL_PATH)/proprietary/system/usr/keylayout/fingerprint.kl:system/usr/keylayout/fingerprint.kl \
    $(LOCAL_PATH)/proprietary/system/usr/keylayout/qwerty.kl:system/usr/keylayout/qwerty.kl \
    $(LOCAL_PATH)/proprietary/system/usr/keylayout/Generic.kl:system/usr/keylayout/Generic.kl \
    $(LOCAL_PATH)/proprietary/system/usr/keylayout/usbaudio.kl:system/usr/keylayout/usbaudio.kl \
    $(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_0b05_Product_4500.kl:system/usr/keylayout/Vendor_0b05_Product_4500.kl \
    $(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_1bad_Product_f016.kl:system/usr/keylayout/Vendor_1bad_Product_f016.kl \
    $(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_1bad_Product_f023.kl:system/usr/keylayout/Vendor_1bad_Product_f023.kl \
    $(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_1bad_Product_f027.kl:system/usr/keylayout/Vendor_1bad_Product_f027.kl \
    $(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_1bad_Product_f036.kl:system/usr/keylayout/Vendor_1bad_Product_f036.kl \
    $(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_1d79_Product_0009.kl:system/usr/keylayout/Vendor_1d79_Product_0009.kl \
    $(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_05ac_Product_0239.kl:system/usr/keylayout/Vendor_05ac_Product_0239.kl \
    $(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_12bd_Product_d015.kl:system/usr/keylayout/Vendor_12bd_Product_d015.kl \
    $(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_18d1_Product_2c40.kl:system/usr/keylayout/Vendor_18d1_Product_2c40.kl \
    $(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_22b8_Product_093d.kl:system/usr/keylayout/Vendor_22b8_Product_093d.kl \
    $(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_045e_Product_028e.kl:system/usr/keylayout/Vendor_045e_Product_028e.kl \
    $(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_046d_Product_b501.kl:system/usr/keylayout/Vendor_046d_Product_b501.kl \
    $(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_046d_Product_c21d.kl:system/usr/keylayout/Vendor_046d_Product_c21d.kl \
    $(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_046d_Product_c21f.kl:system/usr/keylayout/Vendor_046d_Product_c21f.kl \
    $(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_046d_Product_c216.kl:system/usr/keylayout/Vendor_046d_Product_c216.kl \
    $(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_046d_Product_c219.kl:system/usr/keylayout/Vendor_046d_Product_c219.kl \
    $(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_046d_Product_c294.kl:system/usr/keylayout/Vendor_046d_Product_c294.kl \
    $(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_046d_Product_c299.kl:system/usr/keylayout/Vendor_046d_Product_c299.kl \
    $(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_046d_Product_c532.kl:system/usr/keylayout/Vendor_046d_Product_c532.kl \
    $(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_054c_Product_0268.kl:system/usr/keylayout/Vendor_054c_Product_0268.kl \
    $(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_0079_Product_0011.kl:system/usr/keylayout/Vendor_0079_Product_0011.kl \
    $(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_0583_Product_2060.kl:system/usr/keylayout/Vendor_0583_Product_2060.kl \
    $(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_1038_Product_1412.kl:system/usr/keylayout/Vendor_1038_Product_1412.kl \
    $(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_1532_Product_0900.kl:system/usr/keylayout/Vendor_1532_Product_0900.kl \
    $(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_1689_Product_fd00.kl:system/usr/keylayout/Vendor_1689_Product_fd00.kl \
    $(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_1689_Product_fd01.kl:system/usr/keylayout/Vendor_1689_Product_fd01.kl \
    $(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_1689_Product_fe00.kl:system/usr/keylayout/Vendor_1689_Product_fe00.kl \
    $(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_1852_Product_50d2.kl:system/usr/keylayout/Vendor_1852_Product_50d2.kl \
    $(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_1949_Product_0401.kl:system/usr/keylayout/Vendor_1949_Product_0401.kl \
    $(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_2378_Product_100a.kl:system/usr/keylayout/Vendor_2378_Product_100a.kl \
    $(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_2378_Product_1008.kl:system/usr/keylayout/Vendor_2378_Product_1008.kl \
    $(LOCAL_PATH)/proprietary/system/vendor/firmware/BCM4334B0_002.001.013.1837.2355.hcd:system/vendor/firmware/BCM4334B0_002.001.013.1837.2355.hcd \
    $(LOCAL_PATH)/proprietary/system/vendor/firmware/BCM4335C0_003.001.009.0105.0574_Huawei_Plank_ONLY.hcd:system/vendor/firmware/BCM4335C0_003.001.009.0105.0574_Huawei_Plank_ONLY.hcd \
    $(LOCAL_PATH)/proprietary/system/vendor/firmware/dhd_preinit_config.txt:system/vendor/firmware/dhd_preinit_config.txt \
    $(LOCAL_PATH)/proprietary/system/vendor/firmware/fw_bcm4339_apsta_hw.bin:system/vendor/firmware/fw_bcm4339_apsta_hw.bin \
    $(LOCAL_PATH)/proprietary/system/vendor/firmware/fw_bcm4339_hw.bin:system/vendor/firmware/fw_bcm4339_hw.bin \
    $(LOCAL_PATH)/proprietary/system/vendor/firmware/fw_bcm4339_test_hw_apsta.bin:system/vendor/firmware/fw_bcm4339_test_hw_apsta.bin \
    $(LOCAL_PATH)/proprietary/system/vendor/firmware/hifi_6402.img:system/vendor/firmware/hifi_6402.img \
    $(LOCAL_PATH)/proprietary/system/vendor/firmware/hifi_6402_4spk.img:system/vendor/firmware/hifi_6402_4spk.img \
    $(LOCAL_PATH)/proprietary/system/vendor/firmware/libpn547_fw.so:system/vendor/firmware/libpn547_fw.so \
    $(LOCAL_PATH)/proprietary/system/vendor/firmware/nvram4339_hw.txt:system/vendor/firmware/nvram4339_hw.txt \
    $(LOCAL_PATH)/proprietary/system/vendor/firmware/nvram4339_hw_plk_al10.txt:system/vendor/firmware/nvram4339_hw_plk_al10.txt \
    $(LOCAL_PATH)/proprietary/system/vendor/firmware/nvram4339_hw_plk_cl00.txt:system/vendor/firmware/nvram4339_hw_plk_cl00.txt \
    $(LOCAL_PATH)/proprietary/system/vendor/firmware/nvram4339_hw_plk_l01.txt:system/vendor/firmware/nvram4339_hw_plk_l01.txt \
    $(LOCAL_PATH)/proprietary/system/vendor/firmware/nvram4339_hw_plk_l02.txt:system/vendor/firmware/nvram4339_hw_plk_l02.txt \
    $(LOCAL_PATH)/proprietary/system/vendor/firmware/nvram4339_hw_plk_tl00.txt:system/vendor/firmware/nvram4339_hw_plk_tl00.txt \
    $(LOCAL_PATH)/proprietary/system/vendor/firmware/nvram4339_hw_plk_tl00h.txt:system/vendor/firmware/nvram4339_hw_plk_tl00h.txt \
    $(LOCAL_PATH)/proprietary/system/vendor/firmware/nvram4339_hw_plk_ul00.txt:system/vendor/firmware/nvram4339_hw_plk_ul00.txt \
    $(LOCAL_PATH)/proprietary/system/vendor/framework/com.huawei.audioalgo.jar:system/vendor/framework/com.huawei.audioalgo.jar \
    $(LOCAL_PATH)/proprietary/system/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    $(LOCAL_PATH)/proprietary/system/vendor/lib/egl/libGLES_mali.so:system/vendor/lib/egl/libGLES_mali.so \
    $(LOCAL_PATH)/proprietary/system/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so \
    $(LOCAL_PATH)/proprietary/system/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    $(LOCAL_PATH)/proprietary/system/vendor/lib/libbt-vendor.so:system/vendor/lib/libbt-vendor.so \
    $(LOCAL_PATH)/proprietary/system/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    $(LOCAL_PATH)/proprietary/system/vendor/lib/libOpenCL.so.1:system/vendor/lib/libOpenCL.so.1 \
    $(LOCAL_PATH)/proprietary/system/vendor/lib/libOpenCL.so.1.1:system/vendor/lib/libOpenCL.so.1.1 \
    $(LOCAL_PATH)/proprietary/system/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    $(LOCAL_PATH)/proprietary/system/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    $(LOCAL_PATH)/proprietary/system/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    $(LOCAL_PATH)/proprietary/system/vendor/lib64/egl/libGLES_mali.so:system/vendor/lib64/egl/libGLES_mali.so \
    $(LOCAL_PATH)/proprietary/system/vendor/lib64/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib64/mediadrm/libdrmclearkeyplugin.so \
    $(LOCAL_PATH)/proprietary/system/vendor/lib64/libOpenCL.so:system/vendor/lib64/libOpenCL.so \
    $(LOCAL_PATH)/proprietary/system/vendor/lib64/libOpenCL.so.1:system/vendor/lib64/libOpenCL.so.1 \
    $(LOCAL_PATH)/proprietary/system/vendor/lib64/libOpenCL.so.1.1:system/vendor/lib64/libOpenCL.so.1.1 \
    $(LOCAL_PATH)/proprietary/system/vendor/media/LMspeed_508.emd:system/vendor/media/LMspeed_508.emd \
    $(LOCAL_PATH)/proprietary/system/vendor/media/PFFprec_600.emd:system/vendor/media/PFFprec_600.emd \
    $(LOCAL_PATH)/proprietary/system/lib/libomx_vxe.so:system/lib/libomx_vxe.so \
    $(LOCAL_PATH)/proprietary/system/lib/libomx_vxd.so:system/lib/libomx_vxd.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libomx_vxe.so:system/lib64/libomx_vxe.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libomx_vxd.so:system/lib64/libomx_vxd.so \
    $(LOCAL_PATH)/proprietary/system/lib/libomni_directional_algoclient_jni.so:system/lib/libomni_directional_algoclient_jni.so \
    $(LOCAL_PATH)/proprietary/system/lib/libSonyIMX230PdafLibrary.so:system/lib/libSonyIMX230PdafLibrary.so \
    $(LOCAL_PATH)/proprietary/system/miniisp/PLK/chip_det.bin:system/miniisp/PLK/chip_det.bin \
    $(LOCAL_PATH)/proprietary/system/miniisp/PLK/miniBoot2.bin:system/miniisp/PLK/miniBoot2.bin \
    $(LOCAL_PATH)/proprietary/system/miniisp/PLK/TBM_Latour2.bin:system/miniisp/PLK/TBM_Latour2.bin \
    $(LOCAL_PATH)/proprietary/system/lib/libhw_gui.so:system/lib/libhw_gui.so \
    $(LOCAL_PATH)/proprietary/system/lib/libpsxhelper.so:system/lib/libpsxhelper.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libhw_gui.so:system/lib64/libhw_gui.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libpsxhelper.so:system/lib64/libpsxhelper.so \
    $(LOCAL_PATH)/proprietary/system/lib/libpsxuihelper.so:system/lib/libpsxuihelper.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libpsxuihelper.so:system/lib64/libpsxuihelper.so \
    $(LOCAL_PATH)/proprietary/system/lib/libkeymaster1.so:system/lib/libkeymaster1.so \
    $(LOCAL_PATH)/proprietary/system/lib/libkeymaster_messages.so:system/lib/libkeymaster_messages.so \
    $(LOCAL_PATH)/proprietary/system/lib/libkeystore_binder.so:system/lib/libkeystore_binder.so \
    $(LOCAL_PATH)/proprietary/system/lib/libsoftkeymaster.so:system/lib/libsoftkeymaster.so \
    $(LOCAL_PATH)/proprietary/system/lib/libsoftkeymasterdevice.so:system/lib/libsoftkeymasterdevice.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libkeymaster1.so:system/lib64/libkeymaster1.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libkeymaster_messages.so:system/lib64/libkeymaster_messages.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libkeystore_binder.so:system/lib64/libkeystore_binder.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libsoftkeymaster.so:system/lib64/libsoftkeymaster.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libsoftkeymasterdevice.so:system/lib64/libsoftkeymasterdevice.so \
    $(LOCAL_PATH)/proprietary/system/lib/libhelixplayer.so:system/lib/libhelixplayer.so \
    $(LOCAL_PATH)/proprietary/system/lib/libhelixplayerwrapper.so:system/lib/libhelixplayerwrapper.so \
    $(LOCAL_PATH)/proprietary/system/fonts/DroidSansFallback.ttf:system/fonts/DroidSansFallback.ttf \
    $(LOCAL_PATH)/proprietary/system/fonts/MTLmr3m.ttf:system/fonts/MTLmr3m.ttf \
    $(LOCAL_PATH)/proprietary/system/fonts/NanumGothic.ttf:system/fonts/NanumGothic.ttf \
    $(LOCAL_PATH)/proprietary/system/media/audio/ui/VideoRecordEnd.ogg:system/media/audio/ui/VideoRecordEnd.ogg \
    $(LOCAL_PATH)/proprietary/system/lib/libexif.so:system/lib/libexif.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libexif.so:system/lib64/libexif.so \
    $(LOCAL_PATH)/proprietary/system/lib/lib_fpc_tac_shared.so:system/lib/lib_fpc_tac_shared.so \
    $(LOCAL_PATH)/proprietary/system/lib64/lib_fpc_tac_shared.so:system/lib64/lib_fpc_tac_shared.so \
    $(LOCAL_PATH)/proprietary/system/lib/libmusicsniffer.so:system/lib/libmusicsniffer.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libmusicsniffer.so:system/lib64/libmusicsniffer.so \
    $(LOCAL_PATH)/proprietary/system/lib/libBootloaderOeminfo.so:system/lib/libBootloaderOeminfo.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libBootloaderOeminfo.so:system/lib64/libBootloaderOeminfo.so \
    $(LOCAL_PATH)/proprietary/system/lib/libatpswdck.so:system/lib/libatpswdck.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libatpswdck.so:system/lib64/libatpswdck.so \
    $(LOCAL_PATH)/proprietary/system/lib/libAntiTheftService.so:system/lib/libAntiTheftService.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libAntiTheftService.so:system/lib64/libAntiTheftService.so \
    $(LOCAL_PATH)/proprietary/system/lib/libmorpho_memory_allocator.so:system/lib/libmorpho_memory_allocator.so \
    $(LOCAL_PATH)/proprietary/system/lib/libmorpho_panorama_gp.so:system/lib/libmorpho_panorama_gp.so \
    $(LOCAL_PATH)/proprietary/system/lib/libmrc_cg_filters.so:system/lib/libmrc_cg_filters.so \
    $(LOCAL_PATH)/proprietary/system/lib/libmrc_cg_ldc.so:system/lib/libmrc_cg_ldc.so \
    $(LOCAL_PATH)/proprietary/system/lib/libmrc_cg_mfdenoise.so:system/lib/libmrc_cg_mfdenoise.so \
    $(LOCAL_PATH)/proprietary/system/lib/libmrc_cg_mfdenoise_dualcam.so:system/lib/libmrc_cg_mfdenoise_dualcam.so \
    $(LOCAL_PATH)/proprietary/system/lib/libmrc_cg_niceFood.so:system/lib/libmrc_cg_niceFood.so \
    $(LOCAL_PATH)/proprietary/system/lib/libmrc_cg_postprocess.so:system/lib/libmrc_cg_postprocess.so \
    $(LOCAL_PATH)/proprietary/system/lib/libmrc_cg_postprocess_cl.so:system/lib/libmrc_cg_postprocess_cl.so \
    $(LOCAL_PATH)/proprietary/system/lib/libmrc_cg_sz.so:system/lib/libmrc_cg_sz.so \
    $(LOCAL_PATH)/proprietary/system/lib64/librpc.so:system/lib64/librpc.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libviagpsrpc.so:system/lib64/libviagpsrpc.so \
    $(LOCAL_PATH)/proprietary/system/lib/libfidoca.so:system/lib/libfidoca.so \
    $(LOCAL_PATH)/proprietary/system/lib/libfido_hal.so:system/lib/libfido_hal.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libfidoca.so:system/lib64/libfidoca.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libfido_hal.so:system/lib64/libfido_hal.so
